### ISSUE TITLE
rs merge: fail on 'Merging components'

### ISSUE THREAD

**Issue by alektros** [mapbox/robosat#176] opened 2019-07-24 08:59 UTC
Hello! Many thanks to the developers for this amazing framework! It is very helpful!

I faced with problem when use rs merge (stage 'Merging components'):
> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/robosat/tools/__main__.py", line 58, in <module>
    args.func(args)
  File "/usr/src/app/robosat/tools/merge.py", line 79, in main
    area = int(round(project(merged, "epsg:4326", "esri:54009").area))
  File "/usr/src/app/robosat/spatial/core.py", line 21, in project
    project = functools.partial(pyproj.transform, pyproj.Proj(init=source), pyproj.Proj(init=target))
  File "/opt/venv/lib/python3.6/site-packages/pyproj/proj.py", line 295, in __init__
    self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
  File "/opt/venv/lib/python3.6/site-packages/pyproj/crs.py", line 224, in from_user_input
    return cls(**value)
  File "/opt/venv/lib/python3.6/site-packages/pyproj/crs.py", line 146, in __init__
    super(CRS, self).__init__(projstring)
  File "pyproj/_crs.pyx", line 317, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: +init=esri:54009 +type=crs: (Internal Proj Error: proj_create: cannot expand +init=esri:54009 +type=crs)

What is problem? Maybe I have wrong environment setup?

**Comment by daniel-j-h** [comment] 2019-07-24 18:35
Hey, glad you like robosat! :)

It looks like you are running the `rs merge` tool: in it we project into an equal-area projection so that we can calculate the merged shape's area.

Now it seems like pyproj has problems with the equal-area projection and is not able to transform properly. I don't have a solution off the top of my head and it used to work properly before.

I suggest the following:
- see if you can provide a self-contained reproducible test case, that would help us a lot
- downgrade the pyproj dependency to previous versions and see if it works again

**Comment by daniel-j-h** [comment] 2019-09-14 12:13
@alektros any updates from your side here?

**Comment by alektros** [comment] 2019-09-14 12:28
> @alektros any updates from your side here?

Hello! While i am testing and experimenting with other functionality, so i had not back to this issue. But probably, i will work with this issue again in few weeks

**Comment by daniel-j-h** [comment] 2019-10-23 23:23
@alektros any updates here? Can you reproduce with our pre-built docker images?

**Comment by Venka97** [comment] 2019-10-30 09:31
Hey,

I had the same issue, I changed a few lines in the project method of core.py and now it works.

`   #project = functools.partial(pyproj.transform, pyproj.Proj(init=source), pyproj.Proj(init=target))
    transformer = pyproj.Transformer.from_crs(source, target)
    #return shapely.ops.transform(project, shape)
    return shapely.ops.transform(transformer.transform, shape)
`

**Comment by daniel-j-h** [comment] 2019-10-30 21:17
Coolio! Thanks @Venka97 for keeping us posted! :smile: 

Do you want to open a pull request with your suggested changes? Thanks! :hugs:

**Comment by Venka97** [comment] 2019-10-31 09:15
Sure!

**Closed** 2019-11-04 20:25 UTC
